"""Build the shareable artifacts: a dated Markdown report and a live README block.

The README block turns the repo's own front page into a living trend dashboard
(updated by the scheduled workflow) — a screenshot-worthy, link-worthy artifact,
which is exactly the kind of thing that earns stars and backlinks.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .monitor import Event

README_START = "<!--TRENDWATCH:START-->"
README_END = "<!--TRENDWATCH:END-->"
REPORTS_DIR = Path("reports")
README_PATH = Path("README.md")


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def build_markdown(events: list[Event], leaderboards: dict[str, list]) -> str:
    breakouts = [e for e in events if e.kind == "breakout"]
    trending = [e for e in events if e.kind == "trending"]

    lines = [f"# 📊 TrendWatch report — {_now()}", ""]

    if breakouts:
        lines.append("## 🚀 Watchlist breakouts")
        lines.append("")
        for e in breakouts:
            lines.append(f"- {e.detail.replace('*', '**')}")
        lines.append("")

    if trending:
        lines.append("## 🆕 Newly trending")
        lines.append("")
        for e in trending:
            lines.append(f"- {e.detail.replace('*', '**')}")
        lines.append("")

    if not breakouts and not trending:
        lines.append("_No breakouts or new entrants since the last run. All quiet._")
        lines.append("")

    for feed, names in leaderboards.items():
        lines.append(f"## 🔝 {feed} — top {len(names)}")
        lines.append("")
        for i, name in enumerate(names, start=1):
            lines.append(f"{i}. {name}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [TrendWatch](https://github.com/topics/trendwatch) · "
                 "data by [Trends MCP](https://www.trendsmcp.ai)*")
    return "\n".join(lines)


def write_reports(markdown: str) -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    (REPORTS_DIR / "latest.md").write_text(markdown, encoding="utf-8")
    dated = REPORTS_DIR / f"{datetime.now(timezone.utc):%Y-%m-%d}.md"
    dated.write_text(markdown, encoding="utf-8")
    print(f"  ✓ wrote {REPORTS_DIR / 'latest.md'} and {dated}")


def _readme_block(events: list[Event], leaderboards: dict[str, list]) -> str:
    breakouts = [e for e in events if e.kind == "breakout"]
    lines = [README_START, "", f"### 📊 Live trends — updated {_now()}", ""]

    if breakouts:
        lines.append("**🚀 Breakouts on the watchlist**")
        lines.append("")
        for e in breakouts:
            lines.append(f"- {e.detail.replace('*', '**')}")
        lines.append("")

    # show one compact leaderboard so the README always has something live
    if leaderboards:
        feed, names = next(iter(leaderboards.items()))
        top = names[:10]
        lines.append(f"**🔝 {feed} right now**")
        lines.append("")
        lines.append(" · ".join(f"`{n}`" for n in top))
        lines.append("")

    lines.append("<sub>Auto-updated by TrendWatch · powered by "
                 "[Trends MCP](https://www.trendsmcp.ai)</sub>")
    lines.append("")
    lines.append(README_END)
    return "\n".join(lines)


def update_readme(events: list[Event], leaderboards: dict[str, list]) -> None:
    if not README_PATH.exists():
        return
    content = README_PATH.read_text(encoding="utf-8")
    if README_START not in content or README_END not in content:
        print("  · README has no TRENDWATCH markers; skipping live-dashboard update.")
        return
    block = _readme_block(events, leaderboards)
    before = content.split(README_START)[0]
    after = content.split(README_END)[1]
    README_PATH.write_text(before + block + after, encoding="utf-8")
    print("  ✓ updated README live-dashboard block")
